config/routes.rb
Rails.application.routes.draw do

  
  resources :recipes
  resources :categories
  get "/about", to: 'home#about', as: 'about'
  get "/contact", to: 'home#contact', as: 'contact'
  root to: 'home#index'
  get "/admin", controller: 'admin', action: 'index' 

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :recipes
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :category
  validates :title, uniqueness: true
  validates_presence_of :title, :ingredients, :instructions
  
   def self.find_all_by_query(query)
     query = query.downcase
     query = "%#{query}%"
     category = "%#{query}%"
     Recipe.where(['lower(title) like ? 
                  OR lower(ingredients) like ?
                  OR lower(instructions) like ?',
                  query, query, query])
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  def self.authenticate(username, password)
    user = User.where(username: username).first
    user && user.authenticate(password)
  end
  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :cookBookTitle
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception



  def cookBookTitle
    @title = 'Cookbook'
  end
  
  helper_method :current_user
 
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  helper_method :logged_in? 

  def logged_in?
    session[:logged_in]
  end

  private 
    def authenticate
      if user = authenticate_with_http_basic {|user, password| User.authenticate(user, password)}
        session[:user_id] = user.id
        session[:logged_in] = true
      else
        request_http_basic_authentication
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :set_title

  def set_title
    @title = "Categories"
  end
  
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @recipes = @category.recipes
  end

  # GET /category/new
  def new
    @category = Category.new
  end

  # GET /category/1/edit
  def edit
  end

  # POST /category
  # POST /category.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /category/1
  # DELETE /category/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Categories was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:id, :name)
    end
  
  def get_recipes
    @recipes = Recipe.collect{ |c| [c.name, c.id] }
  end  
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @number_of_recipes = Recipe.count
    @title = 'Cookbook'
  end

  def about
  end
  
  def recipes
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :get_categories, :only =>[:new, :edit, :create, :update]
  before_action :authenticate, :except => [:index, :show]
  # GET /recipes
  # GET /recipes.json
  def index
    if params[:q]
      @recipes = Recipe.find_all_by_query(params[:q])
    else
      @recipes = Recipe.all
    end
    @title = 'Recipie'
  end
  
  

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @categories = Category.all.collect{|c| [c.name, c.id]}
  end

  # GET /recipes/1/edit
  def edit
    @categories = Category.all.collect{|c| [c.name, c.id]}
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    
    if @recipe.save
      redirect_to @recipe, notice: 'Recipe was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.includes(:category).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :ingredients, :instructions, :calories, :category_id)
    end
    
    def get_categories
      @categories = Category.all.collect{|c| [c.name, c.id]}
    end
    
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/admin/index.html.erb
You are logged in!

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h4 style="color: red">All fields are required</h4>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Your Recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= time_ago_in_words(category.updated_at) %> ago</td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/categories/show.html.erb
<article>
  <header>
    <h1>Category:</h1>
    <h2><%= @category.name %></h2>
      <% @recipes.each do |recipe| %>
        <p>
          <tr>
            <td><%= recipe.title %></td>
          <tr>
        </p>
      <% end %>    
    [ <%= link_to 'Edit', edit_category_path(@category) %> ]
  </header>

</article>

<p><%= link_to 'Back', categories_path %></p>

app/views/home/index.html.erb
<%= render "/shared/search" %>
<h2>Latest Recipes</h2>
<p>There are <%= @number_of_recipes %> recipes total.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-US">
  
    <head>
    
        <title>
          <%= @title %>
        </title>
        
            <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
            <%= stylesheet_link_tag 'notice', media: 'all', 'data-turbolinks-track' => true %>
            <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
            <%= csrf_meta_tags %>
            
    </head>
    
    <body>
        <div class="container">
        
        <header>
        
            <h1>Our Cookbook</h1>
            
        </header>
        
        <section class="content">
        
            <nav>
                <%=link_to_unless_current 'Home', root_url %>
                <%=link_to_unless_current 'Recipes', recipes_url %>
                <%=link_to_unless_current 'About', about_url %>
                <%=link_to_unless_current 'Categories', categories_url %>
                <% if logged_in? %>
                  You are logged in as <%= current_user.username %>
                <% end %>
            </nav>
            
            <% if notice %>
              <div id="notice">
                <%= notice %>
              </div>
            <% end %>
        
            <%= yield %>
            
        </section>
        
        <footer>
        
            <h4>Copyright <%=Date.today.year %> OurCookbook</h4>
            
        </footer>
        
        </div>
        
    </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h4 style="color: red">All fields are required</h4>
  
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br>
    <%= f.text_area :ingredients %>
  </div>
  <div class="field">
    <%= f.label :instructions %><br>
    <%= f.text_area :instructions %>
  </div>
  <div class="field">
    <%= f.label :calories %><br>
    <%= f.text_area :calories %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.select :category_id, @categories, :include_blank => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<%= render "/shared/search" %>
<p id="notice"><%= notice %></p>

<h1>Listing Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th>Ingredients</th>
      <th>Instructions</th>
      <th>Calories</th>
      <th>Last Updated</th>
      <th colspan="4"></th>

    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.title %></td>
        <td><%= recipe.category.name rescue "No category" %></td>
        <td><%= recipe.ingredients %></td>
        <td><%= recipe.instructions %></td>
        <td><%= recipe.calories %></td>
        <td><%= time_ago_in_words(recipe.updated_at) %> ago</td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if logged_in? %>
  <%= link_to 'New Recipe', new_recipe_path %>
<% end %> 

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @recipe.title %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @recipe.ingredients %>
</p>

<p>
  <strong>Instructions:</strong>
  <%= @recipe.instructions %>
</p>
<h4>Information</h4>
<p>Category: <%= h(@recipe.category.name) rescue 'No category found' %></p>
<p>Calories: <%= @recipe.calories rescue 'No calories entered' %></p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>

app/views/shared/_search.html.erb
<%= form_tag recipes_url, method: :get do %>
  <div class="searchBar">
    <label for="query">Keywords: </label>
    <input type="search" id="query" name="q" value="<%= params[:q] %>">
    <%= select("get", "category", Category.all.collect {|f| [f.name]}, {include_blank: "None"}) %>
    <input type="submit" value="Search">
  </div>
<% end %>